version: '3'

# init command
services:
  web:
    # กำหนด stdin เพราะว่ามี bug create-react-app
    stdin_open: true

    # image structure
    build:
      # เลือก path ของ project ที่จะเอาไปสร้าง image
      # โดย . คือโฟลเดอร์ current ของ docker-compose.yml
      context: .

      # กำหนดว่าอันไหนเป็น Dockerfile เพื่อ struc image
      dockerfile: Dockerfile.dev

    ports:
      - '3000:3000'

    # bind volumes
    volumes:
      - /app/node_modules
      - .:/app
